### ISSUE TITLE
Review

### ISSUE THREAD

**Issue by amunozdev** [fanziano/Rock-Paper-Scissors#1]
Buenas @fanziano primero que nada felicitarte por terminar el desafío, está muy bueno y sé no que le metiste horas

Fijate que enviaste la url de la web (https://fanziano.github.io/Rock-Paper-Scissors/welcome) y lo que tenés que entregar es la url del repo (https://github.com/fanziano/Rock-Paper-Scissors), para que nosotros podamos todo el proyecto y no solo la web

Más allá de ese detalle, el desafío cumple con las condiciones para ser aprobado, éxitos en el próximo mod!!

**Comment by fanziano** [comment]
Hola @alexismunoz1 
Muchas gracias por tu comentario y por mencionarme lo de la url (repo). Consulta: cómo podría hacer p/corregirlo en la página de APX ya que en
https://apx.school/challenges
el link conduce a
https://fanziano.github.io/Rock-Paper-Scissors/welcome
en vez de
https://github.com/fanziano/Rock-Paper-Scissors.
Muchas gracias!

**Comment by amunozdev** [comment]
@fanziano hablame por el discord asi lo solucionamos
